# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON=2.7
    - os: linux
      language: python
      python: 3.4
      env:
        - TOXENV=py34
        - PYTHON=3.4
    - os: linux
      language: python
      python: 3.5
      env:
        - TOXENV=py35
        - PYTHON=3.5
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON=3.6
    - os: linux
      language: python
      dist: xenial
      python: 3.7
      sudo: true
      env:
        - TOXENV=py37
        - PYTHON=3.7
    - os: osx
      languague: generic
      env:
        - PYTHON=2.7
        - TOXENV=py27
    - os: osx
      languague: generic
      env:
        - PYTHON=3.4.8
        - TOXENV=py34
    - os: osx
      languague: generic
      env:
        - PYTHON=3.5.5
        - TOXENV=py35
    - os: osx
      languague: generic
      env:
        - PYTHON=3.6.5
        - TOXENV=py36
    - os: osx
      languague: generic
      env:
      - PYTHON=3.7.1
      - TOXENV=py37

before_install:
    # Change to stdevEclipse_t1568_swig_files branch
    - cd gopath/src/github.com/skycoin/skycoin && git checkout origin/stdevEclipse_t1568_swig_files && cd ${TRAVIS_BUILD_DIR}
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-osx.sh; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
    # Define command aliases
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then eval "alias python${PYCMD_VERSION}=$(pyenv which python${PYCMD_VERSION})" && eval "alias python2.7=$(pyenv which python2.7)"; fi

    # Print system env info
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pyenv versions ; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pyenv which python${PYCMD_VERSION} ; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then eval "python${PYCMD_VERSION} --version" ; fi
    - echo "PATH=$PATH"

install:
    - eval "$(gimme 1.10)"
    
after_failure:
  - cat ./.tox/py35/log/${TOXENV}-*.log

script: make test-ci

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
