# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.5
      env: TOXENV=py35

    - os: osx
      languague: generic
      env: TOXENV=py35
#    - python: 3.4
#      env: TOXENV=py34
#    - python: 3.5
#      env: TOXENV=py35
#    - python: 3.6
#      env: TOXENV=py36

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ~/bin/gimme; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

install:
    - bash ./.travis/install.sh

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

