# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

os: linux
language: python
python:
    - 3.5

matrix:
  include:
      #- os: linux
      #sudo: required
      #python: 3.5
      #env: TOXENV=py35

    - os: osx
      languague: generic
      env: PYTHON=3.5.1
#    - python: 3.4
#      env: TOXENV=py34
#    - python: 3.5
#      env: TOXENV=py35
#    - python: 3.6
#      env: TOXENV=py36

before_install: |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        brew update
        brew install openssl readline
        brew outdated pyenv || brew upgrade pyenv
        brew install pyenv-virtualenv
        brew install yarn
        pyenv install $PYTHON
        brew install python3; fi
        export PYENV_VERSION=$PYTHON
        export PATH="/Users/travis/.pyenv/shims:${PATH}"
        pyenv-virtualenv venv
        source venv/bin/activate
        python --version
    fi
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme; fi
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ~/bin/gimme; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

install:
    #- bash ./.travis/install.sh
    - python -m pip install -U pip
    - python -m easy_install -U setuptools

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

