# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

matrix:
  include:
      - os: osx
        languague: generic
        env: PYTHON=3.4.0

before_install:
    - bash ./.travis/install.sh

install:
    - pyt-hon -m pip install -U pip
    - python -m easy_install -U setuptools
    - pip install -e .[test]

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

