# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

matrix:
  include:
      - os: osx
        languague: generic

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then brew install python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then virtualenv venv -p python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then source venv/bin/activate; fi

install: true

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

