matrix:
  include:
  - os: linux
    language: python
    python: 2.7
    env:
    - TOXENV=py27
    - PYTHON=2.7
  - os: linux
    language: python
    python: 3.4
    env:
    - TOXENV=py34
    - PYTHON=3.4
  - os: linux
    language: python
    python: 3.5
    env:
    - TOXENV=py35
    - PYTHON=3.5
  - os: linux
    language: python
    python: 3.6
    env:
    - TOXENV=py36
    - PYTHON=3.6
  - os: linux
    language: python
    dist: xenial
    python: 3.7
    sudo: true
    env:
    - TOXENV=py37
    - PYTHON=3.7
  - os: osx
    languague: generic
    env:
    - PYTHON=2.7
    - TOXENV=py27
  - os: osx
    languague: generic
    env:
    - PYTHON=3.4.8
    - TOXENV=py34
  - os: osx
    languague: generic
    env:
    - PYTHON=3.5.5
    - TOXENV=py35
  - os: osx
    languague: generic
    env:
    - PYTHON=3.6.5
    - TOXENV=py36
  - os: osx
    languague: generic
    env:
    - PYTHON=3.7.1
    - TOXENV=py37
before_install:
- cd gopath/src/github.com/skycoin/skycoin && git checkout v0.25.0 && cd ${TRAVIS_BUILD_DIR}
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-osx.sh; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PYCMD_VERSION="$(echo ${PYTHON} |
  cut -d . -f 1,2)" ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PYCMD_PATH="$(pyenv which python${PYCMD_VERSION})"
  ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PYCMD_DIRPATH="$( dirname ${PYCMD_PATH}
  )" ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH="${PYCMD_DIRPATH}:/Users/travis/.pyenv/shims:${PATH}"
  ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then eval "alias python${PYCMD_VERSION}=$(pyenv
  which python${PYCMD_VERSION})" && eval "alias python2.7=$(pyenv which python2.7)";
  fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pyenv versions ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pyenv which python${PYCMD_VERSION} ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then eval "python${PYCMD_VERSION} --version"
  ; fi
- echo "PATH=$PATH"
install:
- eval "$(gimme 1.10)"
after_failure:
- cat ./.tox/${TOXENV}/log/${TOXENV}-*.log
script: make test-ci
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
deploy:
  provider: pypi
  user: olemis
  password:
    secure: Lek+1bI8jaYADO5b4oLTirI3xqdYktV/ihyGCraK+Glp/U6FwwlF3ttRpvdT9/YyVRgWEt/jePQxH+COW3WbKh54MZWCMlMKmWc4JTs6zHliAWXecAQSvPDWHjzO0F1iz839MRBfQdBUMh1g7BFi4nC886DS7ts7+p2XXGsWwtI+quOwvZ6bS0M6nMTecG8OtpYCkOAoGZI6JEoDXyIygPR5+TIWXO2QFt7KT+fsircOvDHzdA2YY/oexwUWwLLf7J0qnRm2AEx0dDjpFTCaOr6+VxdjD7F8qDoXePzVEvW7AG6k0Emx3Vuj9JiTgga8qX3ExHSXoomNhiJoOM30UbH00mdT5Fz+6HqYqFieijX/Li2fExqXXp6Za4VHMrwImrXoYQw4350F8b6QzF7E4WouBBysBZIkBEswp69783uU1lGcbU0wnyj8SN6rYIPO03MG1e5HO+Dd9avMtCMdGj3qsNlmfK0v3fAGjrYsStMQtrfOUZGTahrHPh7P3VPB4qmsJ7eNo+lFtLN0I2+ehoqMd3UH+qggdFdLQFGVMe0SWCUV9Aoyxo9vVqbnPzclsmWL44M6YRDIgOtochNiDINbdx/EA/L517GrpSDjZwvhrJkoCE7Wr9m5YcC+x8qQXCpQ4dcYAJ4C+okASAIwtjOai5dQB7TfHJfN5XzSLUI=
  distributions: bdist_wheel
  skip_existing: true
  on:
    tags: true
    repo: skycoin/pyskycoin
