version: 2
jobs:
  manylinux64:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - run: cd $GOPATH/src/github.com/skycoin/pyskycoin/gopath/src/github.com/skycoin/libskycoin && git remote add simelo https://github.com/simelo/libskycoin && git fetch simelo stdevHan_t88_swig_multiple_return && git checkout -f stdevHan_t88_swig_multiple_return
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker build  --build-arg GO_ARCH=amd64 --build-arg ARCH=x86_64 --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/deploy/Dockerfile  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test
      - run: docker build  --build-arg IMAGE=debian --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/test/Dockerfile  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test

  manylinux32:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - run: cd $GOPATH/src/github.com/skycoin/pyskycoin/gopath/src/github.com/skycoin/libskycoin && git remote add simelo https://github.com/simelo/libskycoin && git fetch simelo stdevHan_t88_swig_multiple_return && git checkout -f stdevHan_t88_swig_multiple_return
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker build  --build-arg GO_ARCH=386 --build-arg ARCH=i686 --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/deploy/Dockerfile  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test
      - run: docker build  --build-arg IMAGE=i386/debian --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/test/Dockerfile  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test
  
  manylinuxarmv7:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - run: cd $GOPATH/src/github.com/skycoin/pyskycoin/gopath/src/github.com/skycoin/libskycoin && git remote add simelo https://github.com/simelo/libskycoin && git fetch simelo stdevHan_t88_swig_multiple_return && git checkout -f stdevHan_t88_swig_multiple_return
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker build  --build-arg GO_ARCH=386 --build-arg ARCH=i686 --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/deploy/Dockerfile  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test
      - run: docker build  --build-arg IMAGE=arm32v7/debian:latest --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/test/Dockerfile  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test


  publish-github-release_32:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - run: cd $GOPATH/src/github.com/skycoin/pyskycoin/gopath/src/github.com/skycoin/libskycoin && git remote add simelo https://github.com/simelo/libskycoin && git fetch simelo stdevHan_t88_swig_multiple_return && git checkout -f stdevHan_t88_swig_multiple_return
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: if [[ $CIRCLE_TAG ]]; then   docker build  --build-arg SHA1=$CIRCLE_SHA1 --build-arg GITHUB_OAUTH_TOKEN --build-arg PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME --build-arg PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME --build-arg QEMU_PLATFORM=raspberrypi3 --build-arg VERSION  --file $GOPATH/src/github.com/skycoin/libskycoin/docker/images/circle/Dockerfile  $GOPATH/src/github.com/skycoin/libskycoin -t skydev-deploy ; fi
          

workflows:
  version: 2
  arm_test:
    jobs:
      - manylinux64
      - manylinux32
      - publish-github-release_32

# # Install PyPA Docker images for building multilinux wheels
# - if [ $TRAVIS_OS_NAME == "linux" ]; then make bdist_manylinux_amd64 ; fi
# - if [ $TRAVIS_OS_NAME == "linux" ]; then make bdist_manylinux_i686 ; fi
# - if [ $TRAVIS_OS_NAME == "linux" ]; then python -m pip install twine ; fi
# - if [ $TRAVIS_OS_NAME == "linux" ]; then python -m twine upload -u $PYPITEST_USER -p $PYPITEST_PWD --skip-existing --repository-url https://test.pypi.org/legacy/ dist/* ; fi

# - if [ $TRAVIS_OS_NAME == "linux" ]; then python -m pip install --index-url https://test.pypi.org/simple/ pyskycoin ; fi
# - if [ $TRAVIS_OS_NAME == "linux" ]; then python -m tox ; fi
# - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then docker build  . -t skydev-test ; fi