version: 2
jobs:
  manylinux64:
    docker:
      - image: circleci/golang:1.12
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true
      - run: docker build  --build-arg URL_DEPLOY=https://test.pypi.org/legacy/ --build-arg PYPI_USER=pyskycoin  --build-arg PYPI_PASSWD="prerelease_0.X" --build-arg GO_ARCH=amd64 --build-arg ARCH=x86_64 --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/deploy/Dockerfile  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test

  manylinux32:
    docker:
      - image: circleci/golang:1.12
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true
      - run: docker build  --build-arg URL_DEPLOY=https://test.pypi.org/legacy/ --build-arg PYPI_USER=pyskycoin  --build-arg PYPI_PASSWD="prerelease_0.X" --build-arg GO_ARCH=386 --build-arg ARCH=i686 --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/deploy/Dockerfile  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test
  
  manylinuxarmv7:
    docker:
      - image: circleci/golang:1.12
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true
      - run: docker build  --build-arg URL_DEPLOY=https://test.pypi.org/legacy/ --build-arg PYPI_USER=pyskycoin  --build-arg PYPI_PASSWD="prerelease_0.X" --build-arg ARCH=armv7hf --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/deploy/Dockerfile-arm  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test

  manylinuxaarch64:
    docker:
      - image: circleci/golang:1.12
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true
      - run: docker build  --build-arg URL_DEPLOY=https://test.pypi.org/legacy/ --build-arg PYPI_USER=pyskycoin  --build-arg PYPI_PASSWD="prerelease_0.X" --build-arg ARCH=aarch64 --file $GOPATH/src/github.com/skycoin/pyskycoin/docker/images/deploy/Dockerfile-arm  $GOPATH/src/github.com/skycoin/pyskycoin -t skydev-test

  deploy_all:
    docker:
      - image: circleci/golang:1.12
    working_directory: $GOPATH/src/github.com/skycoin/pyskycoin
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true
      - run: cd $GOPATH/src/github.com/skycoin/pyskycoin/.circleci && bash deploy.sh
          
workflows:
  version: 2
  arm_test:
    jobs:
      - manylinux64
      - manylinux32
      - manylinuxarmv7
      # - manylinuxaarch64 TODO: Not working deploy to test.pypi.org
      - deploy_all